NAME            = "PyExfil"
SLOGAN          = "Stress Testing Detection & Creativity"
VERSION_CODE    = '1.3.3'
VERSION_NAME    = "Harpax"
VERSION         = VERSION_CODE
AUTHORS         = ['tisf']
RELEASE_DATE    = '2020-12-31'
LAST_UPDATE     = '2025-07-01'
URL             = 'https://PyExfil.MoriRT.com'
